### ISSUE TITLE
Realme Gt 2 / pixel os / android 14 not working 

### ISSUE THREAD

**Issue by Yuvi0912** [anonymix007/ExtA2DP#26] opened 2024-12-09 10:51 UTC
The app is showing is please connect a2dp sink device. The module is flashed in magisk and is enabled in Lsposed as well what could be a possible fix. Using Android 14 with pixel os on realme GT 2
![Screenshot_20241209-161733](https://github.com/user-attachments/assets/60257a59-b0df-4c84-ba19-21bff242c968)
![Screenshot_20241209-161536](https://github.com/user-attachments/assets/e5b0717e-b3b1-42bc-94aa-3bc9c9e746a0)
![Screenshot_20241209-161521](https://github.com/user-attachments/assets/37113644-f2a4-4f07-9a79-83e786330efb)

**Comment by anonymix007** [comment] 2024-12-09 13:26
Duplicate of #1 #7 #17 #18 #24

**Closed as not planned by anonymix007** 2024-12-09 13:26 UTC
