### ISSUE TITLE
Nubia Z60 Ultra

### ISSUE THREAD

**Issue by 404MaximWang** [anonymix007/ExtA2DP#23] opened 2024-08-05 01:53 UTC
Hello from Nubia Z60 Ultra (MyOS 14.0 14)
After installing, the audios aren't played on connected Bluetooth devices or wired headphones. All audios are played on speaker at maximum volume and I can't control it. Help!
LSPosed version: 1.9.2(7024)
Apatch version: 0.10.7(10763)
ExtA2DP Release: 3.0.0

**Comment by anonymix007** [comment] 2024-08-05 07:54
I'd recommend using latest alpha version from [here](https://github.com/anonymix007/ExtA2DP/issues/20#issuecomment-2143911402). And you also need to install the companion module. The default one should be working fine. If not, run `dumpsys media.audio_policy | awk '  /^ Config source: / { print $3 }'` as root and upload the printed file here.

**Comment by 404MaximWang** [comment] 2024-08-05 08:28
[audio_policy_configuration[1].txt](https://github.com/user-attachments/files/16492975/audio_policy_configuration.1.txt)
I've installed the companion module and everything is the newest. I've attached the xml file here, Tks.

**Comment by anonymix007** [comment] 2024-08-05 08:40
Please record logs. First reboot the phone, then run `adb logcat > logs.txt` on PC, then reproduce the issue and upload the resulting logs.txt file here.

**Comment by 404MaximWang** [comment] 2024-08-05 11:56
Should I disable bluetooth before recording logs?

**Comment by 404MaximWang** [comment] 2024-08-05 12:11
Keeping the Xposed Module and the magisk module open, I rebooted and got this log.
[logs.txt](https://github.com/user-attachments/files/16495462/logs.txt)

**Comment by 404MaximWang** [comment] 2024-08-05 12:21
[logs.txt](https://github.com/user-attachments/files/16495602/logs.txt)

**Comment by anonymix007** [comment] 2024-08-05 15:30
Logs appear to stop to early, please try again. AFAIR adb exits after the boot succeeded, so you may need to run it more than one time

**Comment by 404MaximWang** [comment] 2024-08-05 16:51
[logs.txt](https://github.com/user-attachments/files/16500496/logs.txt)
I don't konw if this is long enough. Thanks for your heip.

**Comment by anonymix007** [comment] 2024-08-05 17:06
It isn't. For example, there should be more logs from ExtA2DP:
```
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Set codec IDs...
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec SBC stack ID 0 to 0
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec AAC stack ID 1 to 1
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec aptX stack ID 2 to 2
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec aptX HD stack ID 3 to 3
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec LDAC stack ID 4 to 4
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec LC3 stack ID 5 to 5
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec Opus stack ID 6 to 6
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec aptX Adaptive stack ID 7 to 7
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec aptX TWS stack ID 8 to 8
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec LHDC V3 stack ID 9 to 10
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec LHDC V2 stack ID 10 to 11
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec LHDC V5 stack ID 11 to 12
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec LC3plus HR stack ID 12 to 13
04-04 21:32:28.982  9205  9205 D BluetoothAppModuleNative: Java_ru_kirddos_exta2dp_modules_BluetoothAppModule_setCodecIds: Setting codec FLAC stack ID 13 to 14
```

Your issue sounds like something I've seen too many times:
```
07-12 05:21:05.231  1860  2565 E APM::HwModule: createDevice: could not find HW module for device 0080 address 00:02:5B:00:FF:01
07-12 05:21:05.231  2886  3768 E AudioSystem-JNI: Command failed for android_media_AudioSystem_setDeviceConnectionState: -38
07-12 05:21:05.231  2886  3768 I AS.AudioDeviceInventory: APM failed to make available A2DP device addr=00:02:5B:00:FF:01 error=1
```
It should be fixed by installing the correct companion module. Can you upload `/vendor/etc/bluetooth_qti_hearing_aid_audio_policy_configuration.xml`: first without the companion module and then with it?

**Comment by 404MaximWang** [comment] 2024-08-06 02:58
[bluetooth_qti_hearing_aid_audio_policy_configuration.txt](https://github.com/user-attachments/files/16504690/bluetooth_qti_hearing_aid_audio_policy_configuration.txt)
[bluetooth_qti_hearing_aid_audio_policy_configuration_.txt](https://github.com/user-attachments/files/16504691/bluetooth_qti_hearing_aid_audio_policy_configuration_.txt)
I kept the LSPosed module open. The first file was taken without the magisk module and the second was taken with the module activated.

**Comment by anonymix007** [comment] 2024-08-06 14:09
Looks good. Try recording the logs again.

**Comment by 404MaximWang** [comment] 2024-08-07 14:09
[logs.txt](https://github.com/user-attachments/files/16529816/logs.txt)
![Screenshot_20240807_220515](https://github.com/user-attachments/assets/c9c8bde9-12c1-43d6-981d-ee7d7f761816)

![Screenshot_20240807_220908](https://github.com/user-attachments/assets/d88f52f2-6c8e-4850-9957-de6423840576)

**Comment by anonymix007** [comment] 2024-08-07 14:13
You're doing something wrong with the logs. Are you sure `adb logcat` is running while you are reproducing the issue?

**Comment by 404MaximWang** [comment] 2024-08-07 15:14
😰
Yes. I'm sure.
I reproduced the problem for about two minutes and then I tapped on Ctrl+C to stop recording.
😭😭😭

**Comment by anonymix007** [comment] 2024-08-07 15:30
Maybe this is something with apatch then. I only tested it with Magisk.
Can you upload logs from LSPosed?

**Comment by 404MaximWang** [comment] 2024-08-08 01:49
Sadly, while using modules, I couldn't get any useful information in LSPosed logs.
![Screenshot_20240808_090810.jpg](https://github.com/user-attachments/assets/ca37b486-0474-408e-ae50-49dc119205fd)
[LSPosed_2024-08-08T09_09_13.468782.zip](https://github.com/user-attachments/files/16536522/LSPosed_2024-08-08T09_09_13.468782.zip)

**Comment by anonymix007** [comment] 2024-08-08 11:08
This is not what I'd expect to see. Can you try with Magisk?

**Comment by 404MaximWang** [comment] 2024-08-12 15:59
I tried with my Samsung tablet to test if the module could run properly with APatch.
And the app (alpha version) told me that current ROM is not compatible with ExtA2DP .😭😭😭
Given that magisk cannot hide itself well from detection, I dare not use it. Many apps in my region check if the system is rooted before launching. If I use magisk, many apps cannot work. Sorry.

**Comment by anonymix007** [comment] 2024-08-12 16:30
Well, nothing else I can do about this then. LSPosed logs are literally empty with apatch. I'll reopen if you upload logs with Magisk.

**Closed as not planned by anonymix007** 2024-08-12 16:30 UTC

**Comment by anonymix007** [comment] 2024-08-12 16:32
You probably should just wait for MyOS14.5 since it looks like LHDC was added there (at least it appears to be in RMOS9.5)

**Comment by 404MaximWang** [comment] 2024-12-02 11:35
I switched to Kitsune Mask and the module worked. Thanks.
